title: "Random notes"
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://edseek.com" # the base hostname & protocol for your site, e.g. http://example.com

theme: "just-the-docs"
#color_scheme: "dark"
search_enabled: false

aux_links:
  "LinkedIn":
    - "//linkedin.com/in/jboxman"
  "GitHub":
    - "//github.com/jboxman"

footer_content: "Copyright &copy; 2020 Jason Boxman. Distributed by an <a href=\"https://raw.githubusercontent.com/jboxman/jboxman.github.io/master/LICENSE\">MIT license</a>."

ga_tracking: UA-78244275-1

permalink: pretty
exclude: ["_site/", "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
